spring:
  datasource:
    url: ENC(pXcsmNnCAFF1wLjFn06gB2fRPXGA7l6KAIOTkhH+VMcSN9aqVTXOMAHdCmIIndi9WmGPXm+vxXOp7HFrfBSVOF3LVMMSs1kAo5c+LJDEObS6KTmBGHAlPet6yAfW46SyElZBUAUdXwajwjHvGGV45TASUuO6GQZaQVAwmzlCnZbzT7eZXnmfT9qGxAFybf4s)
    driver-class-name: ENC(Xj+3AiBNbuzofoGrUL6BsswpyLKvXfg8TMkvQH9ABWM=)
    username: ENC(pRm6m/xwUBynyPuTzLC9IA==)
    password: ENC(NcxOPp/0TDyqvheh2OYAbDA3UlIYagZi)

  jpa:
    hibernate:
      ddl-auto: ENC(EMAyh9PnsFoAd2aBUqo83oVTUFrMHVnJ)
    properties:
      hibernate:
        show_sql: ENC(HJdpmg2lQ0RVOUtHdr/Qpw==)
        format_sql: ENC(Qm29sYWf4639qNykjJPrpg==)
    open-in-view: ENC(CawC8MEIkG2fZX3IO1AEbg==)

  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace

movie:
  url: ENC(EjEKurhP4qKlumLqA/fkEOMlc8oIHwelo0Z/47qK8fzSwRBVoTOMGhdeEpE+J9lCZAmqcU/RBYPXmzmQMs2Q8RmgbLhPgMT9)
  queryParams:
    key: ENC(Cx71ZQV+s+pPX/HxLDlalms7urInqyC88pQD1q6HMRU=)
    pkid: ENC(u3fPxTfamxI9kYTphfX4PA==)
    where: ENC(Vq52rMc2+vSETUIVGSaVyvNCddkPwfwn)
    start: ENC(FCZ0jlq4gbvE+VubnaNu1w==)
    display: ENC(KeWU+Y1xB9dCc5yvl6jfzQ==)
    sort: ENC(Yly3FARj194mkmTs4My5ug==)
    query: ENC(xfjBBPpb+oHtZBkqCLSwJB/6nXj0llG/gkHvH+O78KA=)

sms:
  api-key: ENC(/i2EH9JlMm6MtTQp5B9Oti9VpU7JSYzmMaZAgd1wbMM=)
  secret-key: ENC(1sjs5pkVgFuBYoYYDpxrkQmlY3VPWjomsrZg2YjFVDNmvuRqNdOfmjrQP/kRS0h6)
  domain: ENC(S7nMZCvMHBwvOgPL79Gq8Ttzmb9ijuUcX31nf3VF0c4Ywp+bZUUAow==)
  sender: ENC(NUatBrcsezp8PIzZq34nFJgdaVRqJZZ2)

