package com.iamjunhyeok.MovieNotifier.constant;

public enum Genre {
    ACTION, ADVENTURE, ANIMATION, BIOGRAPHY, COMEDY, CRIME, DOCUMENTARY, DRAMA, FAMILY, FANTASY, HISTORY, HORROR, MUSIC, MUSICAL, MYSTERY, ROMANCE, SF, SPORT, THRILLER, WAR, WESTERN, ETC
}
